language: php

notifications:
  email: false

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - pear install PHP_CodeSniffer
  - phpenv rehash
  - ./composer.phar install --dev --prefer-source --no-interaction

script:
  ## PHP_CodeSniffer
  - phpcs --standard=PSR2 index.php
  - phpcs --standard=PSR2 api
  - phpcs --standard=PSR2 assets
  ## PHPmd
  - ./vendor/bin/phpmd src/ text codesize,unusedcode,naming,phpmd.xml
  ## PHPUnit
  - ./vendor/bin/phpunit
