language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  ## Composer
  - composer install --prefer-source
  - composer selfupdate --quiet
  ## PHP_CodeSniffer
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  ## PHP_CodeSniffer
  - phpcs --standard=PSR2 -n api/
  ## PHPUnit
  #- phpunit -c ./ --coverage-text