language: php

notifications:
  email: false

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer install --prefer-source
  - composer selfupdate --quiet
  - pear install PHP_CodeSniffer
  - phpenv rehash

script:
  ## PHP_CodeSniffer
  - phpcs --report=summary --standard=PSR2 --ignore=lib documentroot api
  ## PHPmd
  - ./vendor/bin/phpmd documentroot,api text codesize,unusedcode,naming --exclude=lib
  ## PHPUnit
  #- ./vendor/bin/phpunit
